<?php
namespace App;

use Illuminate\Support\Facades\DB;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Booking extends Authenticatable
{
    use Notifiable;
    protected $table = 'clm_booking_master';
    public $timestamps = false;
    protected $fillable = ['id', 'user_fk', 'physician_fk','schedule_fk', 'wt_fk', 'time_slot_fk','price', 'session', 'booking_date','booking_id', 'remark', 'Payment_status','invoice','status','transaction_id','transaction_log','created_date','created_by','updated_date','updated_by','deleted_date','deleted_by','outlet_fk','pax','qrcode','treatement_fees','arrived_status','first_name','last_name','email','mobile','CountryCode','discount'];

  public static function mybooking($type, $user_id, $lang = "") {

        if ($type == 1) {
            if ($lang == '3') {
                $select = "bm.arrived_status,CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id, IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.outlet_fk,'')AS outlet_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(psm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, IFNULL(om.name_chinese,'')AS outletname, IFNULL(om.outlet_id,'')AS outlet_id, IFNULL(om.contact_no,'')AS contact_no, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(cm.name_chinese,'')AS country_name, IFNULL(cs.state_name_chinese,'')AS state_fk, IFNULL(om.city_fk_chinese,'')AS city_name, IFNULL(om.address1_chinese,'')AS address1, IFNULL(om.address2_chinese,'')AS address2, IFNULL(om.postcode,'')AS postcode, IFNULL(om.longitude,'')AS longitude, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type,IFNULL(om.latitude,'')AS latitude, IFNULL(om.latitude,'')AS latitude, IFNULL(psm.type,'')AS type,bm.qrcode,IFNULL(bm.arrived_status,'')AS arrived_status";
            } else if ($lang == '2') {
                $select = "bm.arrived_status,CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id, IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.outlet_fk,'')AS outlet_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(psm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, IFNULL(om.name_malay,'')AS outletname, IFNULL(om.outlet_id,'')AS outlet_id, IFNULL(om.contact_no,'')AS contact_no, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(cm.name_malay,'')AS country_name, IFNULL(cs.state_name_malay,'')AS state_fk, IFNULL(om.city_fk_malay,'')AS city_name, IFNULL(om.address1_malay,'')AS address1, IFNULL(om.address2_malay,'')AS address2, IFNULL(om.postcode,'')AS postcode, IFNULL(om.longitude,'')AS longitude, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type,IFNULL(om.latitude,'')AS latitude, IFNULL(om.latitude,'')AS latitude, IFNULL(psm.type,'')AS type,bm.qrcode,IFNULL(bm.arrived_status,'')AS arrived_status";
            } else {
                $select = "bm.arrived_status,CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id, IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.outlet_fk,'')AS outlet_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(psm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, IFNULL(om.name,'')AS outletname, IFNULL(om.outlet_id,'')AS outlet_id, IFNULL(om.contact_no,'')AS contact_no, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(cm.name,'')AS country_name, IFNULL(cs.state_name,'')AS state_fk, IFNULL(om.city_fk,'')AS city_name, IFNULL(om.address1,'')AS address1, IFNULL(om.address2,'')AS address2, IFNULL(om.postcode,'')AS postcode, IFNULL(om.longitude,'')AS longitude, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type,IFNULL(om.latitude,'')AS latitude, IFNULL(om.latitude,'')AS latitude, IFNULL(psm.type,'')AS type,bm.qrcode,IFNULL(bm.arrived_status,'')AS arrived_status"; 
            }
//and and DATE_FORMAT(bm.booking_date,'%Y-%m-%d') >=
            $query = DB::table('clm_booking_master as bm')->selectRaw($select)
                            ->join('clm_outlet_master as om', function($join) {
                                $join->on('om.id', '=', 'bm.outlet_fk')->where('om.status', '=', '1');
                            })
                            ->leftjoin("clm_country_master as cm", "cm.id", "=", "om.country_fk")
                            ->leftjoin("clm_state_master as cs", "cs.id", "=", "om.state_fk")
                            ->leftjoin('clm_physician_schedule_master as psm', function($join) {
                                $join->on('psm.id', '=', 'bm.schedule_fk');
                            })
                            ->whereRaw("bm.status = 1 and bm.user_fk = " . $user_id . "  and DATE_FORMAT(bm.booking_date,'%Y-%m-%d') >= '" . date('Y-m-d') . "'  and (bm.arrived_status=2 or bm.arrived_status=4 or bm.arrived_status=0) ")
                            ->orderBy('bm.booking_date', 'desc')->orderBy('bm.id', 'DESC')->paginate(10);
        } elseif ($type == 2) {
            if ($lang == '3') {
                $select = "bm.arrived_status,CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id,IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.wt_fk,'')AS wt_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, CONCAT(wtm.tour_id, '-', wtm.city_chinese) AS tour_name, IFNULL(wtm.tour_id,'')AS tour_id, IFNULL(psm.date,'')AS date, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.image,'')AS schedule_image, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type, IFNULL(wtm.address1_chinese,'')AS world_tour_address1, IFNULL(wtm.address2_chinese,'')AS world_tour_address2, IFNULL(wtm.city_chinese,'')AS world_tour_city, IFNULL(wtm.postcode,'')AS world_tour_postcode, IFNULL(cm.name_chinese,'')AS world_tour_country_name, IFNULL(cs.state_name_chinese,'')AS state, IFNULL(wtm.latitude,'')AS world_tour_latitude, IFNULL(wtm.longitude,'')AS world_tour_longitude, IFNULL(wtm.world_tour,'')AS world_tour, IFNULL(psm.date,'')AS schedule_date, IFNULL(psm.max_person,'')AS max_person, IFNULL(psm.used_slot,'')AS schedule_used_slot, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.price,'')AS schedule_price, IFNULL(psm.start_time,'')AS schedule_start_time, IFNULL(psm.end_time,'')AS schedule_end_time, IFNULL(wtm.start_date,'')AS schedule_start_date, IFNULL(wtm.end_date,'')AS scheduleend_date,bm.qrcode,IFNULL(bm.arrived_status,'')AS arrived_status";
            } else if ($lang == '2') {
                $select = "bm.arrived_status,CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id,IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.wt_fk,'')AS wt_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, CONCAT(wtm.tour_id, '-', wtm.city_malay) AS tour_name, IFNULL(wtm.tour_id,'')AS tour_id, IFNULL(psm.date,'')AS date, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.image,'')AS schedule_image, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type, IFNULL(wtm.address1_malay,'')AS world_tour_address1, IFNULL(wtm.address2_malay,'')AS world_tour_address2, IFNULL(wtm.city_malay,'')AS world_tour_city, IFNULL(wtm.postcode,'')AS world_tour_postcode, IFNULL(cm.name_malay,'')AS world_tour_country_name, IFNULL(cs.state_name_malay,'')AS state, IFNULL(wtm.latitude,'')AS world_tour_latitude, IFNULL(wtm.longitude,'')AS world_tour_longitude, IFNULL(wtm.world_tour,'')AS world_tour, IFNULL(psm.date,'')AS schedule_date, IFNULL(psm.max_person,'')AS max_person, IFNULL(psm.used_slot,'')AS schedule_used_slot, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.price,'')AS schedule_price, IFNULL(psm.start_time,'')AS schedule_start_time, IFNULL(psm.end_time,'')AS schedule_end_time, IFNULL(wtm.start_date,'')AS schedule_start_date, IFNULL(wtm.end_date,'')AS scheduleend_date,bm.qrcode,IFNULL(bm.arrived_status,'')AS arrived_status";
            } else {
                $select = "bm.arrived_status,CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id,IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.wt_fk,'')AS wt_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, CONCAT(wtm.tour_id, '-', wtm.city) AS tour_name, IFNULL(wtm.tour_id,'')AS tour_id, IFNULL(psm.date,'')AS date, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.image,'')AS schedule_image, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type, IFNULL(wtm.address1,'')AS world_tour_address1, IFNULL(wtm.address2,'')AS world_tour_address2, IFNULL(wtm.city,'')AS world_tour_city, IFNULL(wtm.postcode,'')AS world_tour_postcode, IFNULL(cm.name,'')AS world_tour_country_name, IFNULL(cs.state_name,'')AS state, IFNULL(wtm.latitude,'')AS world_tour_latitude, IFNULL(wtm.longitude,'')AS world_tour_longitude, IFNULL(wtm.world_tour,'')AS world_tour, IFNULL(psm.date,'')AS schedule_date, IFNULL(psm.max_person,'')AS max_person, IFNULL(psm.used_slot,'')AS schedule_used_slot, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.price,'')AS schedule_price, IFNULL(psm.start_time,'')AS schedule_start_time, IFNULL(psm.end_time,'')AS schedule_end_time, IFNULL(wtm.start_date,'')AS schedule_start_date, IFNULL(wtm.end_date,'')AS scheduleend_date,bm.qrcode,IFNULL(bm.arrived_status,'')AS arrived_status";
            }
// DATE_FORMAT(bm.booking_date,'%Y-%m-%d') >= '" . date('Y-m-d') . "' and bm.user_fk = " . $user_id . "
            $query = DB::table('clm_booking_master as bm')->selectRaw($select)
                            ->join('clm_world_tour_master as wtm', function($join) {
                                $join->on('wtm.id', '=', 'bm.wt_fk')->where('wtm.status', '=', '1');
                            })
                            ->leftjoin("clm_country_master as cm", "cm.id", "=", "wtm.country_fk")
                            ->leftjoin("clm_state_master as cs", "cs.id", "=", "wtm.state")
                            ->join('clm_physician_schedule_master as psm', function($join) {
                                $join->on('psm.id', '=', 'bm.schedule_fk');
                            })
                            ->whereRaw("bm.status = 1 and DATE_FORMAT(bm.booking_date,'%Y-%m-%d') >= '" . date('Y-m-d') . "'  and bm.user_fk = " . $user_id . " and (bm.arrived_status=2 or bm.arrived_status=4 or bm.arrived_status=0) ")
                            ->orderBy('bm.booking_date', 'desc')->orderBy('bm.id', 'desc')->paginate(10);
							
        }
        return $query;
    }
 
	public static function History($lang = "", $type, $user_id) {
        if ($type == 1) {
            if ($lang == '3') {
                $select = "CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as user_name,IFNULL(bm.id,'') AS id, IFNULL(bm.user_fk,'') AS user_fk, IFNULL(bm.physician_fk,'') AS physician_fk, IFNULL(bm.schedule_fk,'') AS schedule_fk, IFNULL(bm.outlet_fk,'') AS outlet_fk, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS price, IFNULL(bm.session,'') AS session, IFNULL(bm.booking_date,'') AS booking_date, IFNULL(bm.remark,'') AS remark, IFNULL(bm.payment_status,'') AS payment_status, IFNULL(bm.invoice,'') AS invoice, IFNULL(bm.pax,'') AS pax, IFNULL(bm.booking_id,'') AS booking_id, IFNULL(bm.status,'') AS status, IFNULL(bm.transaction_id,'') AS transcation_id, IFNULL(bm.transaction_log,'') AS transaction_log, IFNULL(psm.start_date,'') AS schedule_date, IFNULL(psm.max_person,'') AS schedule_max_person, IFNULL(psm.used_slot,'') AS schedule_used_slot, IFNULL(psm.session,'') AS schedule_session, IFNULL(psm.price,'') AS schedule_price, IFNULL(psm.type,'') AS schedule_type, IFNULL(psm.start_time,'') AS schedule_start_time, IFNULL(psm.end_time,'') AS schedule_end_time, IFNULL(psm.chris_leonge_type,'') AS schedule_chris_leonge_type, IFNULL(psm.start_date,'') AS schedule_start_date, IFNULL(psm.end_date,'') AS schedule_end_date, IFNULL(om.name,'') AS outlet_name, IFNULL(om.outlet_id,'') AS outlet_id, IFNULL(om.contact_no,'') AS outlet_contact_no, IFNULL(om.email,'') AS outlet_email, IFNULL(om.country_fk,'') AS outlet_country, IFNULL(om.state_fk,'') AS outlet_state, IFNULL(om.city_fk,'') AS outlet_city, IFNULL(om.address1,'') AS outlet_address1, IFNULL(om.address2,'') AS outlet_address2, IFNULL(om.postcode,'') AS outlet_postcode, IFNULL(om.longitude,'') AS outlet_longitude, IFNULL(om.latitude,'') AS outlet_latitude, IFNULL(om.opening_hour_start,'') AS outlet_opening_hour_start, IFNULL(om.opening_hour_end,'') AS outlet_opening_hour_end, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS outlet_booking_fee, IFNULL(om.remark,'') AS outlet_remark, IFNULL(country.name,'') AS outlet_country_name, CONCAT(om.address1, ', ', om.address2,', ', om.city_fk,', ',om.state_fk,', ',country.name,', ',om.postcode) AS address,CONCAT(country.currency_code,' ',IFNULL(bm.treatement_fees,'')) AS treatment_fee,IFNULL(bm.remark,'') AS remarks,CONCAT('public/upload/','',bm.qrcode) as qrcode";
            } else if ($lang == '2') {
                $select = "CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as user_name,IFNULL(bm.id,'') AS id, IFNULL(bm.user_fk,'') AS user_fk, IFNULL(bm.physician_fk,'') AS physician_fk, IFNULL(bm.schedule_fk,'') AS schedule_fk, IFNULL(bm.outlet_fk,'') AS outlet_fk, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS price, IFNULL(bm.session,'') AS session, IFNULL(bm.booking_date,'') AS booking_date, IFNULL(bm.remark,'') AS remark, IFNULL(bm.payment_status,'') AS payment_status, IFNULL(bm.invoice,'') AS invoice, IFNULL(bm.pax,'') AS pax, IFNULL(bm.booking_id,'') AS booking_id, IFNULL(bm.status,'') AS status, IFNULL(bm.transaction_id,'') AS transcation_id, IFNULL(bm.transaction_log,'') AS transaction_log, IFNULL(psm.start_date,'') AS schedule_date, IFNULL(psm.max_person,'') AS schedule_max_person, IFNULL(psm.used_slot,'') AS schedule_used_slot, IFNULL(psm.session,'') AS schedule_session, IFNULL(psm.price,'') AS schedule_price, IFNULL(psm.type,'') AS schedule_type, IFNULL(psm.start_time,'') AS schedule_start_time, IFNULL(psm.end_time,'') AS schedule_end_time, IFNULL(psm.chris_leonge_type,'') AS schedule_chris_leonge_type, IFNULL(psm.start_date,'') AS schedule_start_date, IFNULL(psm.end_date,'') AS schedule_end_date, IFNULL(om.name,'') AS outlet_name, IFNULL(om.outlet_id,'') AS outlet_id, IFNULL(om.contact_no,'') AS outlet_contact_no, IFNULL(om.email,'') AS outlet_email, IFNULL(om.country_fk,'') AS outlet_country, IFNULL(om.state_fk,'') AS outlet_state, IFNULL(om.city_fk,'') AS outlet_city, IFNULL(om.address1,'') AS outlet_address1, IFNULL(om.address2,'') AS outlet_address2, IFNULL(om.postcode,'') AS outlet_postcode, IFNULL(om.longitude,'') AS outlet_longitude, IFNULL(om.latitude,'') AS outlet_latitude, IFNULL(om.opening_hour_start,'') AS outlet_opening_hour_start, IFNULL(om.opening_hour_end,'') AS outlet_opening_hour_end, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS outlet_booking_fee, IFNULL(om.remark,'') AS outlet_remark, IFNULL(country.name,'') AS outlet_country_name, CONCAT(om.address1, ', ', om.address2,', ', om.city_fk,', ',om.state_fk,', ',country.name,', ',om.postcode) AS address,CONCAT(country.currency_code,' ',IFNULL(bm.treatement_fees,'')) AS treatment_fee,IFNULL(bm.remark,'') AS remarks,CONCAT('public/upload/','',bm.qrcode) as qrcode";
            } else {
                $select = "CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as user_name,IFNULL(bm.id,'') AS id, IFNULL(bm.user_fk,'') AS user_fk, IFNULL(bm.physician_fk,'') AS physician_fk, IFNULL(bm.schedule_fk,'') AS schedule_fk, IFNULL(bm.outlet_fk,'') AS outlet_fk, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS price, IFNULL(bm.session,'') AS session, IFNULL(bm.booking_date,'') AS booking_date, IFNULL(bm.remark,'') AS remark, IFNULL(bm.payment_status,'') AS payment_status, IFNULL(bm.invoice,'') AS invoice, IFNULL(bm.pax,'') AS pax, IFNULL(bm.booking_id,'') AS booking_id, IFNULL(bm.status,'') AS status, IFNULL(bm.transaction_id,'') AS transcation_id, IFNULL(bm.transaction_log,'') AS transaction_log, IFNULL(psm.start_date,'') AS schedule_date, IFNULL(psm.max_person,'') AS schedule_max_person, IFNULL(psm.used_slot,'') AS schedule_used_slot, IFNULL(psm.session,'') AS schedule_session, IFNULL(psm.price,'') AS schedule_price, IFNULL(psm.type,'') AS schedule_type, IFNULL(psm.start_time,'') AS schedule_start_time, IFNULL(psm.end_time,'') AS schedule_end_time, IFNULL(psm.chris_leonge_type,'') AS schedule_chris_leonge_type, IFNULL(psm.start_date,'') AS schedule_start_date, IFNULL(psm.end_date,'') AS schedule_end_date, IFNULL(om.name,'') AS outlet_name, IFNULL(om.outlet_id,'') AS outlet_id, IFNULL(om.contact_no,'') AS outlet_contact_no, IFNULL(om.email,'') AS outlet_email, IFNULL(om.country_fk,'') AS outlet_country, IFNULL(om.state_fk,'') AS outlet_state, IFNULL(om.city_fk,'') AS outlet_city, IFNULL(om.address1,'') AS outlet_address1, IFNULL(om.address2,'') AS outlet_address2, IFNULL(om.postcode,'') AS outlet_postcode, IFNULL(om.longitude,'') AS outlet_longitude, IFNULL(om.latitude,'') AS outlet_latitude, IFNULL(om.opening_hour_start,'') AS outlet_opening_hour_start, IFNULL(om.opening_hour_end,'') AS outlet_opening_hour_end, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS outlet_booking_fee, IFNULL(om.remark,'') AS outlet_remark, IFNULL(country.name,'') AS outlet_country_name, CONCAT(om.address1, ', ', om.address2,', ', om.city_fk,', ',om.state_fk,', ',country.name,', ',om.postcode) AS address,CONCAT(country.currency_code,' ',IFNULL(bm.treatement_fees,'')) AS treatment_fee,IFNULL(bm.remark,'') AS remarks,CONCAT('public/upload/','',bm.qrcode) as qrcode";
            }
            $query = DB::table('clm_booking_master as  bm')->selectRaw($select);
            $query->join('clm_physician_schedule_master as psm', function($join) {
                $join->on('psm.id', '=', 'bm.schedule_fk');
               // $join->whereRaw('psm.status=1 and psm.display=1');
            });
            $query->join('clm_outlet_master as om', function($join) {
                $join->on('om.id', '=', 'bm.outlet_fk');
               
            });
            $query->join('clm_country_master as country', 'country.id', '=', 'om.country_fk');
            $query->leftjoin('clm_state_master as cs', function( $join) {
                $join->on("cs.id", "=", "om.state_fk");
            });
        } elseif ($type == 2) {
            if ($lang == '3') {
                $select = "CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as user_name,IFNULL(bm.id,'') AS id, IFNULL(bm.user_fk,'') AS user_fk, IFNULL(bm.physician_fk,'') AS physician_fk, IFNULL(bm.schedule_fk,'') AS schedule_fk, IFNULL(bm.outlet_fk,'') AS outlet_fk, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS price, IFNULL(bm.session,'') AS session, IFNULL(bm.booking_date,'') AS booking_date, IFNULL(bm.remark,'') AS remark, IFNULL(bm.payment_status,'') AS payment_status, IFNULL(bm.invoice,'') AS invoice, IFNULL(bm.pax,'') AS pax, IFNULL(bm.booking_id,'') AS booking_id, IFNULL(bm.status,'') AS status, IFNULL(bm.transaction_id,'') AS transcation_id, IFNULL(bm.transaction_log,'') AS transaction_log, IFNULL(psm.start_date,'') AS schedule_date, IFNULL(psm.max_person,'') AS schedule_max_person, IFNULL(psm.used_slot,'') AS schedule_used_slot, IFNULL(psm.session,'') AS schedule_session, IFNULL(psm.price,'') AS schedule_price, IFNULL(psm.type,'') AS schedule_type, IFNULL(psm.start_time,'') AS schedule_start_time, IFNULL(psm.end_time,'') AS schedule_end_time, IFNULL(psm.chris_leonge_type,'') AS schedule_chris_leonge_type, IFNULL(psm.start_date,'') AS schedule_start_date, IFNULL(psm.end_date,'') AS schedule_end_date, CONCAT(wt.tour_id, '-', wt.city) AS tour_name, IFNULL(wt.tour_id,'') AS tour_id, IFNULL(wt.image,'') AS world_tour_image, IFNULL(wt.address1,'') AS world_tour_address1, IFNULL(wt.address2,'') AS world_tour_address2, IFNULL(wt.city,'') AS world_tour_city, IFNULL(wt.postcode,'') AS world_tour_postcode, IFNULL(wt.state,'') AS world_tour_state, IFNULL(wt.latitude,'') AS world_tour_latitude, IFNULL(wt.longitude,'') AS world_tour_longitude, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS outlet_booking_fee, IFNULL(wt.max_person,'') AS world_tour_max_person, IFNULL(wt.used_slot,'') AS world_tour_used_slot, IFNULL(wt.world_tour,'') AS world_tour_type, IFNULL(country.currency_code,'') AS world_tour_currency_code, IFNULL(wt.start_date,'') AS world_tour_start_date, IFNULL(wt.end_date,'') AS world_tour_end_date, IFNULL(wt.start_time,'') AS world_tour_start_time, IFNULL(wt.end_time,'') AS world_tour_end_time, IFNULL(country.name,'') AS world_tour_country_name, CONCAT(wt.address1, ', ', wt.address2,', ', wt.city,', ',wt.state,', ',country.name,', ',wt.postcode) AS address,CONCAT(country.currency_code,' ',IFNULL(bm.treatement_fees,'')) AS treatment_fee,IFNULL(bm.remark,'') AS remarks,CONCAT('public/upload/','',bm.qrcode) as qrcode";
            } else if ($lang == '2') {
                $select = "CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as user_name,IFNULL(bm.id,'') AS id, IFNULL(bm.user_fk,'') AS user_fk, IFNULL(bm.physician_fk,'') AS physician_fk, IFNULL(bm.schedule_fk,'') AS schedule_fk, IFNULL(bm.outlet_fk,'') AS outlet_fk, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS price, IFNULL(bm.session,'') AS session, IFNULL(bm.booking_date,'') AS booking_date, IFNULL(bm.remark,'') AS remark, IFNULL(bm.payment_status,'') AS payment_status, IFNULL(bm.invoice,'') AS invoice, IFNULL(bm.pax,'') AS pax, IFNULL(bm.booking_id,'') AS booking_id, IFNULL(bm.status,'') AS status, IFNULL(bm.transaction_id,'') AS transcation_id, IFNULL(bm.transaction_log,'') AS transaction_log, IFNULL(psm.start_date,'') AS schedule_date, IFNULL(psm.max_person,'') AS schedule_max_person, IFNULL(psm.used_slot,'') AS schedule_used_slot, IFNULL(psm.session,'') AS schedule_session, IFNULL(psm.price,'') AS schedule_price, IFNULL(psm.type,'') AS schedule_type, IFNULL(psm.start_time,'') AS schedule_start_time, IFNULL(psm.end_time,'') AS schedule_end_time, IFNULL(psm.chris_leonge_type,'') AS schedule_chris_leonge_type, IFNULL(psm.start_date,'') AS schedule_start_date, IFNULL(psm.end_date,'') AS schedule_end_date, CONCAT(wt.tour_id, '-', wt.city) AS tour_name, IFNULL(wt.tour_id,'') AS tour_id, IFNULL(wt.image,'') AS world_tour_image, IFNULL(wt.address1,'') AS world_tour_address1, IFNULL(wt.address2,'') AS world_tour_address2, IFNULL(wt.city,'') AS world_tour_city, IFNULL(wt.postcode,'') AS world_tour_postcode, IFNULL(wt.state,'') AS world_tour_state, IFNULL(wt.latitude,'') AS world_tour_latitude, IFNULL(wt.longitude,'') AS world_tour_longitude, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS outlet_booking_fee, IFNULL(wt.max_person,'') AS world_tour_max_person, IFNULL(wt.used_slot,'') AS world_tour_used_slot, IFNULL(wt.world_tour,'') AS world_tour_type, IFNULL(country.currency_code,'') AS world_tour_currency_code, IFNULL(wt.start_date,'') AS world_tour_start_date, IFNULL(wt.end_date,'') AS world_tour_end_date, IFNULL(wt.start_time,'') AS world_tour_start_time, IFNULL(wt.end_time,'') AS world_tour_end_time, IFNULL(country.name,'') AS world_tour_country_name, CONCAT(wt.address1, ', ', wt.address2,', ', wt.city,', ',wt.state,', ',country.name,', ',wt.postcode) AS address,CONCAT(country.currency_code,' ',IFNULL(bm.treatement_fees,'')) AS treatment_fee,IFNULL(bm.remark,'') AS remarks,CONCAT('public/upload/','',bm.qrcode) as qrcode";
            } else {
                $select = "CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as user_name,IFNULL(bm.id,'') AS id, IFNULL(bm.user_fk,'') AS user_fk, IFNULL(bm.physician_fk,'') AS physician_fk, IFNULL(bm.schedule_fk,'') AS schedule_fk, IFNULL(bm.outlet_fk,'') AS outlet_fk, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS price, IFNULL(bm.session,'') AS session, IFNULL(bm.booking_date,'') AS booking_date, IFNULL(bm.remark,'') AS remark, IFNULL(bm.payment_status,'') AS payment_status, IFNULL(bm.invoice,'') AS invoice, IFNULL(bm.pax,'') AS pax, IFNULL(bm.booking_id,'') AS booking_id, IFNULL(bm.status,'') AS status, IFNULL(bm.transaction_id,'') AS transcation_id, IFNULL(bm.transaction_log,'') AS transaction_log, IFNULL(psm.start_date,'') AS schedule_date, IFNULL(psm.max_person,'') AS schedule_max_person, IFNULL(psm.used_slot,'') AS schedule_used_slot, IFNULL(psm.session,'') AS schedule_session, IFNULL(psm.price,'') AS schedule_price, IFNULL(psm.type,'') AS schedule_type, IFNULL(psm.start_time,'') AS schedule_start_time, IFNULL(psm.end_time,'') AS schedule_end_time, IFNULL(psm.chris_leonge_type,'') AS schedule_chris_leonge_type, IFNULL(psm.start_date,'') AS schedule_start_date, IFNULL(psm.end_date,'') AS schedule_end_date, CONCAT(wt.tour_id, '-', wt.city) AS tour_name, IFNULL(wt.tour_id,'') AS tour_id, IFNULL(wt.image,'') AS world_tour_image, IFNULL(wt.address1,'') AS world_tour_address1, IFNULL(wt.address2,'') AS world_tour_address2, IFNULL(wt.city,'') AS world_tour_city, IFNULL(wt.postcode,'') AS world_tour_postcode, IFNULL(wt.state,'') AS world_tour_state, IFNULL(wt.latitude,'') AS world_tour_latitude, IFNULL(wt.longitude,'') AS world_tour_longitude, CONCAT(country.currency_code,' ',IFNULL(bm.price,'')) AS outlet_booking_fee, IFNULL(wt.max_person,'') AS world_tour_max_person, IFNULL(wt.used_slot,'') AS world_tour_used_slot, IFNULL(wt.world_tour,'') AS world_tour_type, IFNULL(country.currency_code,'') AS world_tour_currency_code, IFNULL(wt.start_date,'') AS world_tour_start_date, IFNULL(wt.end_date,'') AS world_tour_end_date, IFNULL(wt.start_time,'') AS world_tour_start_time, IFNULL(wt.end_time,'') AS world_tour_end_time, IFNULL(country.name,'') AS world_tour_country_name, CONCAT(wt.address1, ', ', wt.address2,', ', wt.city,', ',wt.state,', ',country.name,', ',wt.postcode) AS address,CONCAT(country.currency_code,' ',IFNULL(bm.treatement_fees,'')) AS treatment_fee,IFNULL(bm.remark,'') AS remarks,CONCAT('public/upload/','',bm.qrcode) as qrcode";
            }
            $query = DB::table('clm_booking_master as bm')->selectRaw($select);
            $query->join('clm_physician_schedule_master as psm', function($join) {
                $join->on('psm.tour_id', '=', 'bm.wt_fk');
                $join->whereRaw('psm.status=1 and psm.display=1');
            });
            $query->join('clm_world_tour_master as wt', function($join) {
                $join->on('wt.id', '=', 'bm.wt_fk');
                //$join->whereRaw('wt.wstatus=1 and wt.status=1');
            });
            $query->join('clm_country_master as country', 'country.id', '=', 'wt.country_fk');
            $query->leftjoin('clm_state_master as cs', function( $join) {
                $join->on("cs.id", "=", "wt.state");
            });
        }
        $query->join('clm_customer_master as cm', 'cm.id', '=', 'bm.user_fk');
        $query->join('clm_physician_master as pm', function( $join) {
            $join->on("pm.id", "=", "bm.physician_fk")->whereRaw("pm.status=1 and pm.active_status=1");
        });

        $query->where('bm.user_fk', $user_id);
        $query->where('bm.booking_date','<=', date('Y-m-d'));
        $query->where('bm.status', 1);
        $query->whereRaw('bm.schedule_fk =psm.id');
        $query->whereRaw('((bm.arrived_status = 1 or bm.arrived_status = 3) or ((bm.arrived_status=2 or bm.arrived_status=4 or bm.arrived_status=0) and DATE_FORMAT(bm.booking_date,"%Y-%m-%d") < "' . date('Y-m-d') . '"))');
        $query->orderBy('bm.booking_date', 'desc');
        $data = $query->paginate(10);
		
        return $data;
    }
	
	
	
		public static function booking_details($bookingId, $type, $lang = ""){
	if ($type == 1) {
				if($lang == '3') {
					$select =("CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id, IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.outlet_fk,'')AS outlet_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, IFNULL(om.name_chinese,'')AS outletname, IFNULL(om.outlet_id,'')AS outlet_id, IFNULL(psm.session,'')AS schedule_session,  IFNULL(om.contact_no,'')AS contact_no, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(cm.name_chinese,'')AS country_name, IFNULL(cs.state_name_chinese,'')AS state_fk, IFNULL(om.city_fk_chinese,'')AS city_name, IFNULL(om.address1_chinese,'')AS address1, IFNULL(om.address2_chinese,'')AS address2, IFNULL(om.postcode,'')AS postcode, IFNULL(om.longitude,'')AS longitude, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type,IFNULL(om.latitude,'')AS latitude, IFNULL(om.latitude,'')AS latitude, IFNULL(psm.type,'')AS type,bm.qrcode,IFNULL(bm.treatement_fees,'') AS treatment_fee, IFNULL(bm.arrived_status,'') AS reschedule");
				} else if($lang == '2') {
					$select =("CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id, IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.outlet_fk,'')AS outlet_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, IFNULL(om.name_malay,'')AS outletname, IFNULL(om.outlet_id,'')AS outlet_id, IFNULL(psm.session,'')AS schedule_session,  IFNULL(om.contact_no,'')AS contact_no, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(cm.name_malay,'')AS country_name, IFNULL(cs.state_name_chinese,'')AS state_fk, IFNULL(om.city_fk_malay,'')AS city_name, IFNULL(om.address1_malay,'')AS address1, IFNULL(om.address2_malay,'')AS address2, IFNULL(om.postcode,'')AS postcode, IFNULL(om.longitude,'')AS longitude, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type,IFNULL(om.latitude,'')AS latitude, IFNULL(om.latitude,'')AS latitude, IFNULL(psm.type,'')AS type,bm.qrcode,IFNULL(bm.treatement_fees,'') AS treatment_fee, IFNULL(bm.arrived_status,'') AS reschedule");
				} else {
					$select =("CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id, IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.outlet_fk,'')AS outlet_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, IFNULL(om.name,'')AS outletname, IFNULL(om.outlet_id,'')AS outlet_id, IFNULL(om.contact_no,'')AS contact_no,  IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(cm.name,'')AS country_name, IFNULL(cs.state_name,'')AS state_fk, IFNULL(om.city_fk,'')AS city_name, IFNULL(om.address1,'')AS address1, IFNULL(om.address2,'')AS address2, IFNULL(om.postcode,'')AS postcode, IFNULL(om.longitude,'')AS longitude, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type,IFNULL(om.latitude,'')AS latitude, IFNULL(om.latitude,'')AS latitude, IFNULL(psm.type,'')AS type,bm.qrcode,IFNULL(bm.treatement_fees,'') AS treatment_fee, IFNULL(bm.arrived_status,'') AS reschedule");
				}
	$query = DB::table('clm_booking_master as bm')->selectRaw($select);
						$query->join('clm_outlet_master as om',function($join){
							$join->on('om.id','=','bm.outlet_fk')->where('om.status',1);
						});
						$query->leftjoin('clm_country_master as cm', 'cm.id','=','om.country_fk');
						$query->leftjoin('clm_state_master as cs', 'cs.id','=','om.state_fk');
			} elseif ($type == 2) {
				if($lang == '3') {
					$select =("CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id,IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.wt_fk,'')AS wt_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, CONCAT(wtm.tour_id, '-', wtm.city_chinese) AS tour_name, IFNULL(wtm.tour_id,'')AS tour_id, IFNULL(psm.date,'')AS date, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.image,'')AS schedule_image, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type, IFNULL(wtm.address1_chinese,'')AS world_tour_address1, IFNULL(wtm.address2_chinese,'')AS world_tour_address2, IFNULL(wtm.city_chinese,'')AS world_tour_city, IFNULL(wtm.postcode,'')AS world_tour_postcode, IFNULL(cm.name_chinese,'')AS world_tour_country_name, IFNULL(cs.state_name_chinese,'')AS state, IFNULL(wtm.latitude,'')AS world_tour_latitude, IFNULL(wtm.longitude,'')AS world_tour_longitude, IFNULL(wtm.world_tour,'')AS world_tour, IFNULL(psm.date,'')AS schedule_date, IFNULL(psm.max_person,'')AS max_person, IFNULL(psm.used_slot,'')AS schedule_used_slot, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.price,'')AS schedule_price, IFNULL(psm.start_time,'')AS start_time, IFNULL(psm.end_time,'')AS end_time, IFNULL(wtm.start_date,'')AS schedule_start_date, IFNULL(wtm.end_date,'')AS scheduleend_date,bm.qrcode,IFNULL(bm.treatement_fees,'') AS treatment_fee, IFNULL(bm.arrived_status,'') AS arrived_status");
				} else if($lang == '2') {
					$select =("CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id,IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.wt_fk,'')AS wt_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, CONCAT(wtm.tour_id, '-', wtm.city_malay) AS tour_name, IFNULL(wtm.tour_id,'')AS tour_id, IFNULL(psm.date,'')AS date, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.image,'')AS schedule_image, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type, IFNULL(wtm.address1_malay,'')AS world_tour_address1, IFNULL(wtm.address2_malay,'')AS world_tour_address2, IFNULL(wtm.city_malay,'')AS world_tour_city, IFNULL(wtm.postcode,'')AS world_tour_postcode, IFNULL(cm.name_malay,'')AS world_tour_country_name, IFNULL(cs.state_name_malay,'')AS state, IFNULL(wtm.latitude,'')AS world_tour_latitude, IFNULL(wtm.longitude,'')AS world_tour_longitude, IFNULL(wtm.world_tour,'')AS world_tour, IFNULL(psm.date,'')AS schedule_date, IFNULL(psm.max_person,'')AS max_person, IFNULL(psm.used_slot,'')AS schedule_used_slot, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.price,'')AS schedule_price, IFNULL(psm.start_time,'')AS schedule_start_time, IFNULL(psm.end_time,'')AS schedule_end_time, IFNULL(wtm.start_date,'')AS schedule_start_date, IFNULL(wtm.end_date,'')AS scheduleend_date,bm.qrcode,IFNULL(bm.treatement_fees,'') AS treatment_fee, IFNULL(bm.arrived_status,'') AS arrived_status");
				} else {
					$select =("CONCAT(IFNULL(bm.first_name,''),' ',IFNULL(bm.last_name,'')) as bName,IFNULL(bm.id,'')AS id,IFNULL(bm.booking_id,'')AS booking_id, IFNULL(bm.user_fk,'')AS user_fk, IFNULL(bm.physician_fk,'')AS physician_fk, IFNULL(bm.schedule_fk,'')AS schedule_fk, IFNULL(bm.wt_fk,'')AS wt_fk, IFNULL(bm.price,'')AS booking_price, IFNULL(bm.session,'')AS session, IFNULL(bm.booking_date,'')AS booking_date, IFNULL(bm.remark,'')AS remark, IFNULL(bm.Payment_status,'')AS Payment_status, IFNULL(bm.invoice,'')AS invoice, IFNULL(bm.pax,'')AS pax, IFNULL(bm.transaction_id,'')AS transaction_id, IFNULL(bm.transaction_log,'')AS transaction_log, CONCAT(wtm.tour_id, '-', wtm.city) AS tour_name, IFNULL(wtm.tour_id,'')AS tour_id, IFNULL(psm.date,'')AS date, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.image,'')AS schedule_image, IFNULL(psm.chris_leonge_type,'')AS chris_leonge_type, IFNULL(wtm.address1,'')AS world_tour_address1, IFNULL(wtm.address2,'')AS world_tour_address2, IFNULL(wtm.city,'')AS world_tour_city, IFNULL(wtm.postcode,'')AS world_tour_postcode, IFNULL(cm.name,'')AS world_tour_country_name, IFNULL(cs.state_name,'')AS state, IFNULL(wtm.latitude,'')AS world_tour_latitude, IFNULL(wtm.longitude,'')AS world_tour_longitude, IFNULL(wtm.world_tour,'')AS world_tour, IFNULL(psm.date,'')AS schedule_date, IFNULL(psm.max_person,'')AS max_person, IFNULL(psm.used_slot,'')AS schedule_used_slot, IFNULL(psm.session,'')AS schedule_session, IFNULL(psm.price,'')AS schedule_price, IFNULL(psm.start_time,'')AS schedule_start_time, IFNULL(psm.end_time,'')AS schedule_end_time, IFNULL(wtm.start_date,'')AS schedule_start_date, IFNULL(wtm.end_date,'')AS scheduleend_date,bm.qrcode,IFNULL(bm.treatement_fees,'') AS treatment_fee, IFNULL(bm.arrived_status,'') AS arrived_status");
				}
			$query = DB::table('clm_booking_master as bm')->selectRaw($select);
						$query->join('clm_world_tour_master as wtm',function($join){
							$join->on('wtm.id','=','bm.wt_fk')->where('wtm.status',1)->where('wtm.wstatus',1);
						});
						$query->leftjoin('clm_country_master as cm', 'cm.id','=','wtm.country_fk');
						$query->leftjoin('clm_state_master as cs', 'cs.id','=','wtm.state');
			}
			$query->leftjoin('clm_physician_schedule_master as psm',function($join){
						$join->on('psm.id','=','bm.schedule_fk')->where('psm.status',1)->where('psm.display',1);
					});
					$query->where('bm.status', '1');
					$query->where('bm.id', $bookingId);
					$data = $query->get();
	return $data;


	}
 }

?>   